//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernizationDemo.EfTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTransaction
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string LectorInvoiceUrl { get; set; }
        public string Discriminator { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string Description { get; set; }
        public string InvoiceUrl { get; set; }
        public Nullable<decimal> CustomAccountTransaction_Amount { get; set; }
        public Nullable<System.DateTime> CustomAccountTransaction_CreatedDate { get; set; }
        public Nullable<System.DateTime> CustomAccountTransaction_PaidDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Course Cours { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
