//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernizationDemo.EfTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.AccountTransactions = new HashSet<AccountTransaction>();
            this.Attachments = new HashSet<Attachment>();
            this.CourseDates = new HashSet<CourseDate>();
            this.CourseReminders = new HashSet<CourseReminder>();
            this.DiscountCoupons = new HashSet<DiscountCoupon>();
            this.Orders = new HashSet<Order>();
            this.Recordings = new HashSet<Recording>();
            this.Lectors = new HashSet<Lector>();
        }
    
        public int Id { get; set; }
        public System.DateTime BeginDate { get; set; }
        public bool IsEveningCourse { get; set; }
        public int NumberOfDays { get; set; }
        public int CourseTemplateId { get; set; }
        public string LocationNotes { get; set; }
        public string ContentNotes { get; set; }
        public int Type { get; set; }
        public Nullable<int> LocationId { get; set; }
        public decimal Price { get; set; }
        public bool IsApproved { get; set; }
        public bool IsDeleted { get; set; }
        public int SupplierId { get; set; }
        public string CourseSubtitle { get; set; }
        public bool IsRegistrationClosed { get; set; }
        public bool AllowOnlinePayments { get; set; }
        public bool AllowCashPayments { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public decimal Margin { get; set; }
        public decimal PricePerDay { get; set; }
        public int MinimumNumberOfAttendees { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTransaction> AccountTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseDate> CourseDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseReminder> CourseReminders { get; set; }
        public virtual CourseTemplate CourseTemplate { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Location Location { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountCoupon> DiscountCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recording> Recordings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lector> Lectors { get; set; }
    }
}
