//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernizationDemo.EfTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTemplateRelation
    {
        public int Id { get; set; }
        public int CourseTemplateId { get; set; }
        public int RelatedCourseTemplateId { get; set; }
        public int Type { get; set; }
    
        public virtual CourseTemplate CourseTemplate { get; set; }
        public virtual CourseTemplate CourseTemplate1 { get; set; }
    }
}
