//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernizationDemo.EfTests.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DotNetCollegeContext : DbContext
    {
        public DotNetCollegeContext()
            : base("name=DotNetCollegeContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountTransaction> AccountTransactions { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<AttendeeRegistration> AttendeeRegistrations { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CourseDate> CourseDates { get; set; }
        public virtual DbSet<CourseReminder> CourseReminders { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseTemplateRelation> CourseTemplateRelations { get; set; }
        public virtual DbSet<CourseTemplate> CourseTemplates { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DiscountCoupon> DiscountCoupons { get; set; }
        public virtual DbSet<InvoiceLine> InvoiceLines { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Lector> Lectors { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MainCategory> MainCategories { get; set; }
        public virtual DbSet<OrderAvailableDate> OrderAvailableDates { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PrivateCourseRequest> PrivateCourseRequests { get; set; }
        public virtual DbSet<Recording> Recordings { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    }
}
