//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernizationDemo.EfTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.AccountTransactions = new HashSet<AccountTransaction>();
            this.InvoiceLines = new HashSet<InvoiceLine>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string Notes { get; set; }
        public bool IsFinalInvoice { get; set; }
        public string FileUrl { get; set; }
        public string Currency { get; set; }
        public decimal TotalAmount { get; set; }
        public int SupplierId { get; set; }
        public int AddressId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public bool IsCorrectionInvoice { get; set; }
        public string CorrectedInvoiceNumber { get; set; }
        public decimal TotalAmountWithoutVAT { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTransaction> AccountTransactions { get; set; }
        public virtual Address Address { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders1 { get; set; }
    }
}
