//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernizationDemo.EfTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lector()
        {
            this.Accounts = new HashSet<Account>();
            this.Courses = new HashSet<Course>();
            this.PrivateCourseRequests = new HashSet<PrivateCourseRequest>();
        }
    
        public int Id { get; set; }
        public string Bio { get; set; }
        public string Blog { get; set; }
        public string LinkedIn { get; set; }
        public string Twitter { get; set; }
        public int UserId { get; set; }
        public string UrlName { get; set; }
        public string Website { get; set; }
        public int Order { get; set; }
        public string AvatarUrl { get; set; }
        public bool IsDeleted { get; set; }
        public decimal CommissionPrice { get; set; }
        public decimal CommissionPercent { get; set; }
        public Nullable<int> CommissionAccountId { get; set; }
        public int DefaultSupplierId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Account Account { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivateCourseRequest> PrivateCourseRequests { get; set; }
    }
}
