//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernizationDemo.EfTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.AttendeeRegistrations = new HashSet<AttendeeRegistration>();
            this.OrderAvailableDates = new HashSet<OrderAvailableDate>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> BillingAddressId { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> CourseTemplateId { get; set; }
        public Nullable<int> DiscountCouponId { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal VATRate { get; set; }
        public bool HasVAT { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string Currency { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal DiscountPercent { get; set; }
        public Nullable<int> ProformaInvoiceId { get; set; }
        public Nullable<int> FinalInvoiceId { get; set; }
        public Nullable<System.DateTime> CanceledDate { get; set; }
        public string BraintreeTransactionId { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendeeRegistration> AttendeeRegistrations { get; set; }
        public virtual Course Cours { get; set; }
        public virtual CourseTemplate CourseTemplate { get; set; }
        public virtual DiscountCoupon DiscountCoupon { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Invoice Invoice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAvailableDate> OrderAvailableDates { get; set; }
    }
}
